import '../styles/globals.css'
import type { Metadata } from 'next' // philippa or default?
import { Inter } from 'next/font/google' // p or default?
import React from 'react';
import Navbar from '../components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// thats javascript i think?
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }


interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout: React.FC<LayoutProps> ({ children }) {
  return (
    <html lang="en">
      <head />
      <Navbar />
       <body className={inter.className}>{children}</body>
    </html>
  );
};

